-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgG7EL6NJqAsdhW4OXgHjZNJttvOc2ihLy8zgDc/nnjSGgCgYIKoZIzj0DAQehRANCAAQtUdH7y2xyDEWWVCVR4DC9PY5FTd0Z7Lls+zGnriCIfUVW2FMx8TeZrLKT4LrHlITa0r/l3Lprry6ce/MEh2br
-----END PRIVATE KEY-----