# Uncomment the next line to define a global platform for your project
#platform :ios, '.0'


target 'Scholarly' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Scholarly
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
    pod 'Firebase/Storage'
    pod 'Firebase/Database'
    pod 'Firebase/Auth'
    pod 'IQKeyboardManagerSwift'

  target 'ScholarlyTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
    pod 'Firebase/Storage'
    pod 'Firebase/Database'
    pod 'Firebase/Auth'
    pod 'IQKeyboardManagerSwift'
  end

  target 'ScholarlyUITests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
    pod 'Firebase/Storage'
    pod 'Firebase/Database'
    pod 'Firebase/Auth'
    pod 'IQKeyboardManagerSwift'
  end

end
